-- MySQL Script generated by MySQL Workbench
-- 06/10/16 10:15:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unicesumar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unicesumar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unicesumar` DEFAULT CHARACTER SET utf8 ;
USE `unicesumar` ;

-- -----------------------------------------------------
-- Table `unicesumar`.`DOCENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`DOCENTE` (
  `ID_DOCENTE` INT NOT NULL AUTO_INCREMENT,
  `NM_DOCENTE` VARCHAR(100) NOT NULL,
  `TP_TITULACAO` ENUM('consultor', 'tecnico', 'bacharel', 'especialista', 'mestre', 'doutor') NULL,
  PRIMARY KEY (`ID_DOCENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unicesumar`.`DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`DISCIPLINA` (
  `ID_DISCIPLINA` INT NOT NULL AUTO_INCREMENT,
  `NM_DISCIPLINA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_DISCIPLINA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unicesumar`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`ALUNO` (
  `ID_ALUNO` INT NOT NULL AUTO_INCREMENT,
  `NM_ALUNO` VARCHAR(100) NOT NULL,
  `DT_NASCIMENTO` DATE NOT NULL,
  PRIMARY KEY (`ID_ALUNO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unicesumar`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`CURSO` (
  `ID_CURSO` INT NOT NULL AUTO_INCREMENT,
  `NM_CURSO` VARCHAR(100) NOT NULL,
  `TP_TIPO_CURSO` ENUM('tecnico', 'bacharelado', 'especializacao', 'mestrado', 'doutorado') NOT NULL,
  PRIMARY KEY (`ID_CURSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unicesumar`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`TURMA` (
  `ID_TURMA` INT NOT NULL AUTO_INCREMENT,
  `NM_TURMA` VARCHAR(100) NOT NULL,
  `NR_ANO` INT NOT NULL,
  `NR_SEMESTRE` INT NOT NULL,
  `CURSO_ID` INT NOT NULL,
  PRIMARY KEY (`ID_TURMA`),
  INDEX `fk_TURMA_CURSO1_idx` (`CURSO_ID` ASC),
  CONSTRAINT `fk_TURMA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `unicesumar`.`CURSO` (`ID_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unicesumar`.`DISCIPLINA_DOCENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`DISCIPLINA_DOCENTE` (
  `DISCIPLINA_ID_DISCIPLINA` INT NOT NULL,
  `DOCENTE_ID_DOCENTE` INT NOT NULL,
  PRIMARY KEY (`DISCIPLINA_ID_DISCIPLINA`, `DOCENTE_ID_DOCENTE`),
  INDEX `fk_DISCIPLINA_has_DOCENTE_DOCENTE1_idx` (`DOCENTE_ID_DOCENTE` ASC),
  INDEX `fk_DISCIPLINA_has_DOCENTE_DISCIPLINA_idx` (`DISCIPLINA_ID_DISCIPLINA` ASC),
  CONSTRAINT `fk_DISCIPLINA_has_DOCENTE_DISCIPLINA`
    FOREIGN KEY (`DISCIPLINA_ID_DISCIPLINA`)
    REFERENCES `unicesumar`.`DISCIPLINA` (`ID_DISCIPLINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DISCIPLINA_has_DOCENTE_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID_DOCENTE`)
    REFERENCES `unicesumar`.`DOCENTE` (`ID_DOCENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unicesumar`.`CURSO_DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`CURSO_DISCIPLINA` (
  `CURSO_ID` INT NOT NULL,
  `DISCIPLINA_ID` INT NOT NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`CURSO_ID`, `DISCIPLINA_ID`, `DOCENTE_ID`),
  INDEX `fk_CURSO_has_DISCIPLINA_DISCIPLINA1_idx` (`DISCIPLINA_ID` ASC),
  INDEX `fk_CURSO_has_DISCIPLINA_CURSO1_idx` (`CURSO_ID` ASC),
  INDEX `fk_CURSO_DISCIPLINA_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_CURSO_has_DISCIPLINA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `unicesumar`.`CURSO` (`ID_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_has_DISCIPLINA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_ID`)
    REFERENCES `unicesumar`.`DISCIPLINA` (`ID_DISCIPLINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_DISCIPLINA_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `unicesumar`.`DOCENTE` (`ID_DOCENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unicesumar`.`TURMA_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unicesumar`.`TURMA_ALUNO` (
  `TURMA_ID` INT NOT NULL,
  `ALUNO_ID` INT NOT NULL,
  PRIMARY KEY (`TURMA_ID`, `ALUNO_ID`),
  INDEX `fk_TURMA_has_ALUNO_ALUNO1_idx` (`ALUNO_ID` ASC),
  INDEX `fk_TURMA_has_ALUNO_TURMA1_idx` (`TURMA_ID` ASC),
  CONSTRAINT `fk_TURMA_has_ALUNO_TURMA1`
    FOREIGN KEY (`TURMA_ID`)
    REFERENCES `unicesumar`.`TURMA` (`ID_TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TURMA_has_ALUNO_ALUNO1`
    FOREIGN KEY (`ALUNO_ID`)
    REFERENCES `unicesumar`.`ALUNO` (`ID_ALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
